apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: private-eth
  source:
    repoURL: https://prometheus-community.github.io/helm-charts 
    chart: prometheus
    targetRevision: 25.27.0
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/0xawaz/private-eth/main/deploy/monitor/helm/prometheus-v2.51.2.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true