apiVersion: v1
kind: Service
metadata:
  namespace: eth
  name: execution
  labels:
    app: execution
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8551
    targetPort: 8551
  selector:
    app: execution