apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: private-eth
  source:
    repoURL: https://github.com/kubernetes/ingress-nginx
    targetRevision: HEAD
    path: charts/ingress-nginx
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/0xawaz/private-eth/main/deploy/web/nginx-ingress/nginx-ingress-values-1.10.0.yaml
  destination:
    namespace: web
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
