apiVersion: v1
kind: ConfigMap
metadata:
  name: consensus-config
  namespace: eth
data:
  config.yml: |
    CONFIG_NAME: private-eth-testnet
    PRESET_BASE: custom
    
    # Genesis
    GENESIS_FORK_VERSION: 0x20000089
    
    ELECTRA_FORK_VERSION: 0x30000000
    
    # Altair
    ALTAIR_FORK_EPOCH: 0
    ALTAIR_FORK_VERSION: 0x20000090
    
    # Merge
    BELLATRIX_FORK_EPOCH: 0
    BELLATRIX_FORK_VERSION: 0x20000091
    TERMINAL_TOTAL_DIFFICULTY: 0
    
    # Capella
    CAPELLA_FORK_EPOCH: 0
    CAPELLA_FORK_VERSION: 0x20000092
    MAX_WITHDRAWALS_PER_PAYLOAD: 16
    
    DENEB_FORK_VERSION: 0x20000093
    
    # Time parameters
    SECONDS_PER_SLOT: 12
    SLOTS_PER_EPOCH: 6
    
    # Deposit contract
    DEPOSIT_CONTRACT_ADDRESS: 0xF4C11A4D088E57e4B27b657C6BeC99A1C7869C1F