apiVersion: v1
kind: Service
metadata:
  namespace: eth
  name: beacon
  labels:
    app: beacon
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000
  selector:
    app: beacon