name: Build and publish a Docker image
on:
  push:
    paths:
        - '.github/workflows/build-docker-image.yml'
    tags:
        - v*
env:
  AWS_REGION: us-east-1
  AWS_ECR_REPOSITORY: 0xawaz/private-eth
  IMAGE_TAG: v1.0.0
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./build/
          file: ./build/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.AWS_ECR_REPOSITORY }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false